import {
  Calculator,
  GitCompare,
  FileText,
  FileSearch,
  FileJson,
  KeyRound,
  Lock,
  Code,
  Database,
  Braces,
  CreditCard,
  Building2,
  Terminal,
  Pipette,
  Ticket,
  Clock,
  FileCode,
} from "lucide-react"
import type { Tool } from "@/lib/types"

export const tools: Tool[] = [
  {
    id: "contador",
    name: "Contador de Caracteres",
    path: "/contador",
    icon: <Calculator className="h-4 w-4 mr-2" />,
    description: "Conte caracteres, palavras e linhas em qualquer texto.",
  },
  {
    id: "comparador",
    name: "Comparador de .env",
    path: "/comparador",
    icon: <GitCompare className="h-4 w-4 mr-2" />,
    description: "Compare dois arquivos .env e identifique diferenças entre eles.",
  },
  {
    id: "comparador-textos",
    name: "Comparador de Textos",
    path: "/comparador-textos",
    icon: <FileText className="h-4 w-4 mr-2" />,
    description: "Compare dois textos e visualize as diferenças entre eles.",
  },
  {
    id: "localizar-substituir",
    name: "Localizar e Substituir",
    path: "/localizar-substituir",
    icon: <FileSearch className="h-4 w-4 mr-2" />,
    description: "Encontre e substitua trechos específicos em qualquer texto.",
  },
  {
    id: "env-to-json",
    name: ".env para JSON",
    path: "/env-to-json",
    icon: <FileJson className="h-4 w-4 mr-2" />,
    description: "Converta arquivos .env para o formato JSON.",
  },
  {
    id: "json-to-env",
    name: "JSON para .env",
    path: "/json-to-env",
    icon: <FileJson className="h-4 w-4 mr-2" />,
    description: "Converta arquivos JSON para o formato .env.",
  },
  {
    id: "hash-senha",
    name: "Hash de Senhas",
    path: "/hash-senha",
    icon: <KeyRound className="h-4 w-4 mr-2" />,
    description: "Gere e verifique hashes de senhas com o algoritmo Apache MD5.",
  },
  {
    id: "gerador-senha",
    name: "Gerador de Senhas",
    path: "/gerador-senha",
    icon: <Lock className="h-4 w-4 mr-2" />,
    description: "Crie senhas fortes e seguras com diversos critérios.",
  },
  {
    id: "openssl-senha",
    name: "Senhas OpenSSL",
    path: "/openssl-senha",
    icon: <Terminal className="h-4 w-4 mr-2" />,
    description: "Gere senhas seguras usando o método OpenSSL.",
  },
  {
    id: "comparador-javascript",
    name: "Comparador de JavaScript",
    path: "/comparador-javascript",
    icon: <Code className="h-4 w-4 mr-2" />,
    description: "Compare códigos JavaScript e verifique se são equivalentes.",
  },
  {
    id: "mongo-ids",
    name: "Extrator de IDs MongoDB",
    path: "/mongo-ids",
    icon: <Database className="h-4 w-4 mr-2" />,
    description: "Extraia IDs de uma coleção MongoDB para uso em consultas.",
  },
  {
    id: "json-formatter",
    name: "Formatador de JSON",
    path: "/json-formatter",
    icon: <Braces className="h-4 w-4 mr-2" />,
    description: "Formate e visualize JSON com syntax highlighting.",
  },
  {
    id: "gerador-cpf",
    name: "Gerador de CPF",
    path: "/gerador-cpf",
    icon: <CreditCard className="h-4 w-4 mr-2" />,
    description: "Gere números de CPF válidos para testes e desenvolvimento.",
  },
  {
    id: "gerador-cnpj",
    name: "Gerador de CNPJ",
    path: "/gerador-cnpj",
    icon: <Building2 className="h-4 w-4 mr-2" />,
    description: "Gere números de CNPJ válidos para testes e desenvolvimento.",
  },
  {
    id: "coletor-cores",
    name: "Coletor de Cores",
    path: "/coletor-cores",
    icon: <Pipette className="h-4 w-4 mr-2" />,
    description: "Capture e analise cores de imagens ou crie sua própria paleta.",
  },
  {
    id: "gerador-jira",
    name: "Gerador de Links Jira",
    path: "/gerador-jira",
    icon: <Ticket className="h-4 w-4 mr-2" />,
    description: "Gere links formatados para tickets do Jira em formato Markdown.",
  },
  {
    id: "timestamp-converter",
    name: "Conversor de Timestamp",
    path: "/timestamp-converter",
    icon: <Clock className="h-4 w-4 mr-2" />,
    description: "Converta timestamps Unix para datas legíveis e veja quando expiram.",
  },
  {
    id: "remover-comentarios",
    name: "Remover Comentários JS",
    path: "/remover-comentarios",
    icon: <FileCode className="h-4 w-4 mr-2" />,
    description: "Remova todos os comentários de código JavaScript.",
  },
]

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id)
}
